### ISSUE TITLE
question: how can I choose the golang version?

### ISSUE THREAD

**Issue by robsonpeixoto** [batect/golang-bundle#43]

**Comment by charleskorn** [comment]
Hi @robsonpeixoto, this isn't something that's supported directly at the moment - the version of the bundle that you reference is tied to a particular Golang version. 

[The releases page](https://github.com/batect/golang-bundle/releases) lists which bundle version has which version of Golang.

Do you need to be able to select a particular version of Golang? I'm interested in understanding more about your particular situation.

**Comment by robsonpeixoto** [comment]
Being honest, is only curiosity. I knew this tools today and I'm reading some examples just to learn more.
O just miss a way to pass parameters to bundle. It will help a lot to create more reusable bundles.
For example, at the company that I work has a lot of Go project and should be create to not worry about what the bundle version I need to use to work with the Go version X.Y.Z.
I really love the strategy of use containers to run the commands.

About the parameters, maybe it is a good inspiration: https://taskfile.dev/#/usage?id=calling-another-task

**Comment by charleskorn** [comment]
Interesting - I've been thinking of bundles as super opinionated (including versions) with limited customisation. That way, you can upgrade the bundle and get everything upgraded alongside it. 

Are there any other kinds of customisation you'd want to be able to do for bundles?

**Comment by robsonpeixoto** [comment]
Now, only version.
